
INSERT INTO `service` VALUES ('5', '10', 'Service des Innovations Technologiques et de Développement des Systèmes de Gestion de l\'Éducation ', null, 'SITDSGE', '1', '1');
INSERT INTO `service` VALUES ('6', '10', 'Service de la Maintenance, des Entretiens et de la Gestion du Parc Informatique\r\n', null, 'SMEGPI', '1', '1');
INSERT INTO `service` VALUES ('7', '16', 'Service de la Planification et du Partenariat \r\n', null, 'SPP', '1', '1');
INSERT INTO `service` VALUES ('8', '16', 'Service de la Formation et de l\'Encadrement ', null, 'SFE', '1', '1');
INSERT INTO `service` VALUES ('9', '16', 'Service des Études et de la Communication pour le Changement de Comportement', null, 'SECCC', '1', '1');
INSERT INTO `service` VALUES ('10', '16', 'Service de l\'Éducation Environnementale\r\n', null, 'SEE', '1', '1');
INSERT INTO `service` VALUES ('11', '11', 'Service des Affaires Générales \r\n', null, 'SAG', '1', '1');
INSERT INTO `service` VALUES ('12', '11', 'Service de la coordination et du suivi des activités', null, 'SCSA', '1', '1');
INSERT INTO `service` VALUES ('13', '9', 'Service des Affaires Générales \r\n', null, 'SAG', '1', '1');
INSERT INTO `service` VALUES ('14', '9', 'Service de la Coordination et du Suivi des Activités\r\n', null, 'SCSA', '1', '1');
INSERT INTO `service` VALUES ('15', '20', 'Service des Affaires Générales \r\n', null, 'SAG', '1', '1');
INSERT INTO `service` VALUES ('16', '20', 'Service de la Gestion des emplois, des Effectifs et des Compétences \r\n', null, 'SGEEC', '1', '1');
INSERT INTO `service` VALUES ('17', '20', 'Service de la Gestion Administrative du Personnel \r\n', null, 'SGAP', '1', '1');
INSERT INTO `service` VALUES ('18', '20', 'Service des Soldes \r\n', null, 'SSO', '1', '1');
INSERT INTO `service` VALUES ('19', '20', 'Service Médico-Social\r\n', null, 'SMSO', '1', '1');
INSERT INTO `service` VALUES ('20', '13', 'Service de la Construction et des Maintenances des Infrastructures Scolaires \r\n', null, 'SCMIS', '1', '1');
INSERT INTO `service` VALUES ('21', '13', 'Service de la Construction et des Maintenances des Infrastructures Administratives \r\n', null, 'SCMIA', '1', '1');
INSERT INTO `service` VALUES ('22', '13', 'Service des Domaines Scolaires et Administratifs\r\n', null, 'SDSA', '1', '1');
INSERT INTO `service` VALUES ('23', '14', 'Service de l\'Éducation de la Petite Enfance \r\n', null, 'SEPE', '1', '1');
INSERT INTO `service` VALUES ('24', '14', 'Service d\'Appui au Pilotage des Établissements \r\n', null, 'SAPE', '1', '1');
INSERT INTO `service` VALUES ('25', '14', 'Service des Intrants Scolaires \r\n', null, 'SIS', '1', '1');
INSERT INTO `service` VALUES ('26', '14', 'Service de la Santé et de l\'Alimentation Scolaire\r\n', null, 'SSAS', '1', '1');
INSERT INTO `service` VALUES ('27', '18', 'Service d\'Appui au Pilotage des Etablissements \r\n', null, 'SAPE', '1', '1');
INSERT INTO `service` VALUES ('28', '18', 'Service des Intrants Scolaires \r\n', null, 'SIS', '1', '1');
INSERT INTO `service` VALUES ('29', '18', 'Service de Santé des Jeunes\r\n', null, 'SSJ', '1', '1');
INSERT INTO `service` VALUES ('31', '22', 'Service de l\'Education et Formation à distance\r\n', null, 'SEFA', '1', '1');
INSERT INTO `service` VALUES ('32', '22', 'Service des Formations initiales et continues\r\n\r\n', null, 'SFIC', '1', '1');
INSERT INTO `service` VALUES ('33', '19', 'Service de l\'Organisation des Examens \r\n', null, 'SOE', '1', '1');
INSERT INTO `service` VALUES ('34', '19', 'Service des Diplômes et des Certifications \r\n', null, 'SDC', '1', '1');
INSERT INTO `service` VALUES ('35', '19', 'Service des Evaluations des Epreuves\r\n', null, 'SEE', '1', '1');
INSERT INTO `service` VALUES ('36', '21', 'Service de Développement des Curricula \r\n', null, 'SDC', '1', '1');
INSERT INTO `service` VALUES ('37', '21', 'Service des Matériels Didactiques et des Intrants \r\n', null, 'SMDI', '1', '1');
INSERT INTO `service` VALUES ('38', '21', 'Service des Etudes et des Recherches Pédagogiques\r\n', null, 'SERP', '1', '1');
INSERT INTO `service` VALUES ('39', '23', 'Service de l\'Encadrement Scolaire \r\n', null, 'SES', '1', '1');
INSERT INTO `service` VALUES ('40', '23', 'Service de l\'Inspection Pédagogique\r\n', null, 'SIP', '1', '1');
INSERT INTO `service` VALUES ('41', '17', 'Service de l\'Education Inclusive \r\n', null, 'SEI', '1', '1');
INSERT INTO `service` VALUES ('42', '17', 'Service de l\'Alphabétisation \r\n', null, 'SA', '1', '1');
INSERT INTO `service` VALUES ('43', '17', 'Service de l\'Orientation Scolaire et Professionnelle\r\n', null, 'SOSP', '1', '1');
INSERT INTO `service` VALUES ('44', '24', 'Service des Affaires Administratives \r\n', null, 'SAA', '1', '1');
INSERT INTO `service` VALUES ('45', '24', 'Service du Budget \r\n', null, 'SBU', '1', '1');
INSERT INTO `service` VALUES ('46', '24', 'Service de la Logistique\r\n', null, 'SLOG', '1', '1');
INSERT INTO `service` VALUES ('47', '12', 'Service de la Statistique et de la Gouvernance du Système d\'Information \r\n', null, 'SSGSI', '0', '1');
INSERT INTO `service` VALUES ('48', '12', 'Service des Études et d\'Évaluation de la Politique Éducative \r\n', null, 'SEEPE', '0', '1');
INSERT INTO `service` VALUES ('49', '12', 'Service d\'appui à la Micro-Planification \r\n', null, 'SAMP', '0', '1');
INSERT INTO `service` VALUES ('50', '12', 'Service de la Programmation et du Suivi du Système éducatif \r\n', null, 'SPSSE', '0', '1');
INSERT INTO `service` VALUES ('51', '12', 'Service de la Gestion des Risques et Catastrophes\r\n', null, 'SGRC', '0', '1');
INSERT INTO `service` VALUES ('52', '15', 'Service des Études et de la Législation \r\n', null, 'SEL', '1', '1');
INSERT INTO `service` VALUES ('53', '15', 'Service de la Documentation \r\n', null, 'SDO', '1', '1');
INSERT INTO `service` VALUES ('54', '15', 'Service du Contentieux\r\n', null, 'SCO', '1', '1');
INSERT INTO `service` VALUES ('55', '28', 'Service des Affaires Générales \r\n', null, 'SAG', '1', '1');
INSERT INTO `service` VALUES ('56', '28', 'Service Administratif et Financière\r\n', null, 'SAF', '1', '1');
INSERT INTO `service` VALUES ('57', '28', 'Service Assurance Scolaire \r\n', null, 'SAS', '1', '1');
INSERT INTO `service` VALUES ('58', '28', 'Service Prevention et Documentation\r\n', null, 'SPD', '1', '1');
INSERT INTO `service` VALUES ('59', '32', 'Service des Autorisations, Tutelle & Contrôle', null, 'SATC', '1', '1');
INSERT INTO `service` VALUES ('60', '32', 'Service Administratif et Financier', null, 'SAF', '1', '1');
INSERT INTO `service` VALUES ('61', '32', 'Service d\'Appui au Développement et du Partenariat ', null, 'SADP', '1', '1');
INSERT INTO `service` VALUES ('62', '8', 'Service Relations Internationales et des Partenariats', null, 'SRIP', '1', '1');
INSERT INTO `service` VALUES ('63', '8', 'Service des activités Péri et Para Scolaires\r\n', null, 'SAPPS', '1', '1');
INSERT INTO `service` VALUES ('64', '10', 'Rattaché direction', null, 'DIR-DSI', '1', '1');
INSERT INTO `service` VALUES ('65', '12', 'Rattaché direction', null, 'DIR-DPE', '0', '1');
INSERT INTO `service` VALUES ('66', '14', 'Rattaché direction', null, 'DIR-DEFPE', '1', '1');
INSERT INTO `service` VALUES ('67', '15', 'Rattaché direction', null, 'DIR-DAJ', '1', '1');
INSERT INTO `service` VALUES ('68', '21', 'Bureau des Affaires Général\r\n', null, 'DIR-DCRP', '1', '1');
INSERT INTO `service` VALUES ('69', '19', 'Bureau de direction ', null, 'DIR-DEXAMC', '1', '1');
INSERT INTO `service` VALUES ('70', '20', 'Rattaché direction', null, 'DIR-DRH', '1', '1');